config/routes.rb
Rails.application.routes.draw do
  get '/campaigns', to: 'campaigns#new'
  root 'campaigns#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def new; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.slim
h1 Create new campaign
form#new_campaign_form
  .level-one
    .form-group
      label Title
      input.form-control type="text"
    .form-group
      label Description
      textarea.form-control placeholder=("Enter as much information here as possible to describe your campaign and what you are trying to achieve. Others will see this description unless the campaign is accessible to collaborators only.") rows="6" type="text"
      small.form-text
        | Surround content with an asterisk on each side to make it
        i  italic
        |  Surround content with two asterisks on each side to make it
        b  bold
    .actions.pull-right
      input#one-next.btn.btn-primary type="button" value="Next"
  .level-two.mt-5
    .form-group
      label This campaign will be accessible to:
    .campaign-visibility
      .form-group
        label.radio-inline
          input.mr-2 checked="" name="optradio" type="radio"
          | Everyone
        p This campaign will be visible to other PolicyMogul users and may be indexed by search engines. Specific documents, collaborators and other information you choose can be made available to campaign collaborators only.
      .form-group
        label.radio-inline
          input.mr-2 checked="" name="optradio" type="radio"
          | Parliamentarians and collaborators only
        p PolicyMogul maintains a list of MPs and peers, and allows them and their staff to view campaigns related to their interests. Specific documents, collaborators and other information you choose can be made available to campaign collaborators only.
      .form-group
        label.radio-inline
          input.mr-2 checked="" name="optradio" type="radio"
          | Collaborators only
        p This campaign will not be displayed to others; you will need to invite specific people in order to collaborate with them.
    .actions.pull-right
      input#two-prev.btn.btn-primary.mr-2 type="button" value="Previous"
      input#two-next.btn.btn-primary type="button" value="Next"
  .level-three.mt-5
    .form-group
      label Tags that describe this campaign:
      .selected_tag_list
        a.label.label--tag data-tag=("Air conditioning")
          | Air Traffic Control&nbsp;
          span.close ×
      input.form-control placeholder=("Type to add more tags...") type="text"
      .select-scroll-box
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  AIDS
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Air Fares
        .custom-control.custom-checkbox
          input.custom-control-input checked="checked" type="checkbox"
          label.custom-control-label for="customCheck"  Air Traffic Control
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Albania
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Alcohal (Drink driving)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Alcohal (Licensing)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Alfa Group
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Alzheimers
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Anesthetics
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Animals (All issues)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Animals (Cattle)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Animals (Chickens)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Animals (Dangerous dogs)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Animals (Experimentation/testing)
        .custom-control.custom-checkbox
          input.custom-control-input type="checkbox"
          label.custom-control-label for="customCheck"  Animals (Feed)
    .actions.pull-right
      input#three-prev.btn.btn-primary.mr-2 type="button" value="Previous"
      input.btn.btn-primary data-disable-with=("Sign in") name="commit" type="submit" value="Save"

app/views/campaigns/new.html.slim
.col-sm-12.main
  .content
    .row
      .col-md-9.form-container
        == render 'form'
      .col-md-3
        == link_to campaigns_path, class: 'btn-link' do
          i.fa.fa-long-arrow-left
          | Back to campaigns

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand.top-bar
  .collapse.navbar-collapse
    ul
      li.mobile-menu
        button.navbar-toggler.p-0.border-0.d-inline-block data-toggle="offcanvas" type="button"
          span.hamburger
    a.logo-box href="javascript:void(0);"
      == image_tag 'logo.png', class: 'logo', height: "32", width:"137"
    ul.navbar-nav.logged-in.ml-auto
      li#notification-list.nav-item.dropdown
        a.nav-link aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          span.notification-counter-container
            i.fa.fa-bell-o
        .dropdown-menu.notifications-dropdown.dropdown-menu-right aria-labelledby="notifications-dropdown"
          a.dropdown-item.p-2 href="#"  You don't have any pending notifications
      li.nav-item.dropdown.account-menu
        a#account-dropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"  test@mailinator.com
        .dropdown-menu aria-labelledby="account-dropdown"
          a.dropdown-item href="#"  Profile
          a.dropdown-item data-method="delete" href="#" rel="nofollow"  Sign out

app/views/layouts/_sidebar.html.slim
#navbarsExampleDefault.sidebar.offcanvas-collapse.navbar-collapse
  span.fa.fa-close.close1
  a.logo-box href="javascript:void(0);"
    == image_tag 'logo.png', class: 'logo', height: "32", width: "137"
  ul.nav.nav-sidebar
    li.nav-item.dashboard_con
      == link_to 'Home', '/', class: 'nav-link'
    li.nav-item.campaigns_con.active
      == link_to 'Campaigns', campaigns_path, class: 'nav-link'
    li.nav-item.organisations_con
      a.nav-link href="#"  Organisations
    li.nav-item.profiles_con
      a.nav-link href="#"  Profile
  .bottom
    ul.nav.tandcs
      li
        a href="#"  Terms &amp; conditions
      li
        a href="#"  Business terms &amp; conditions
      li
        a href="#"  Privacy policy
    p.copy © PolicyMogul 2019
    a.sign-out data-method="delete" href="/users/sign_out" rel="nofollow"  Sign out

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    title PolicyMogul
    == csrf_meta_tags
    == csp_meta_tag
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    == render 'layouts/header'
    .container-fluid
      .row.m-0
        == render 'layouts/sidebar'
        == yield